# Handling Missing Value.
To handle missing value in our data, we some built in functions in numpy.

These Functions help in finding missing value and make the correct.

It is useful in working and building Machine learning models.

### isnan() Method
It detect missing/ null value and returns boolean value.


In [11]:
import numpy as np 

arr1 = np.array([1,2, np.nan, 4, np.nan])

# If there is null or mising value exist it will return True in place of that value.
new_arr = np.isnan(arr1)

print(arr1)
print(new_arr)

[ 1.  2. nan  4. nan]
[False False  True False  True]


### nan_to_num() method
It help convert the missing/null value within array with specified finit number.

In [12]:
arr1 = np.array([1,2, np.nan, 4, np.nan])

# # It will convert the null value to 5
cleaned_arr = np.nan_to_num(arr1, nan = 5)        # Defaul value for nan is 0

print(cleaned_arr)

[1. 2. 5. 4. 5.]


In [13]:
arr1 = np.array([1,2, np.nan, 4, np.nan])

# It will convert the null value to 0
cleaned_arr = np.nan_to_num(arr1) 

print(cleaned_arr)

[1. 2. 0. 4. 0.]


### isinf() Method
It help detect infinite value in array, and return boolean value.

In [16]:
arr1 = np.array([1,2, np.inf, 4, np.inf])

# It will reurn True if there is infinite value and the rest will return False.
new_arr = np.isinf(arr1)

print(new_arr)

[False False  True False  True]


### Replace infinite value.
To Replace infinite value with finite value use nan_to_num() method.

In [19]:
arr1 = np.array([1,2, np.inf, 4, -np.inf])

# The new finite value is pass to parameter (posinf) and (neginf) in case negative vale.
cleaned_arr = np.nan_to_num(arr1, posinf = 10, neginf = -15)

print(cleaned_arr)

[  1.   2.  10.   4. -15.]
