# NumPy Introduction
NumPy is a Python library used for working with arrays. NumPy stands for Numerical Python

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and we can use it freely. It is also used for working with arrays


## Why Use NumPy
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

In [3]:
# First we have to import numpy
import numpy

# Create numpy array.
my_arr = numpy.array([1, 2, 3, 4, 5])

print(my_arr)

[1 2 3 4 5]


### Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [5]:
# NumPy is usually imported under the np alias
import numpy as np

my_arr = np.array([1, 2, 3, 4, 5])

print(my_arr)

# To check the type
print(type(my_arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# NOTE. To create an ndarray, we can pass a list, tuple or any array-like object into the array() method,
# and it will be converted into an ndarray

In [7]:
import numpy as np

# Use a tuple to create a NumPy array
my_arr = np.array((1, 2, 3, 4, 5))

print(my_arr)


[1 2 3 4 5]


### Checking NumPy Version
The version string is stored under __version__ attribute.


In [8]:
import numpy as np

print(np.__version__)

2.1.3
