# NumPy Array Indexing
Array indexing is the same as accessing an array element.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.



In [1]:
import numpy as np

my_arr = np.array([1, 2, 3, 4, 5])

print(my_arr[0])
print(my_arr[1])
print(my_arr[3])

1
2
4


### Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [5]:
import numpy as np

my_arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(my_arr)
print("Access 2nd element of first row: ",my_arr[0, 1])

[[1 2 3 4]
 [5 6 7 8]]
Access 2nd element of first row:  2


In [8]:
import numpy as np

my_arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(my_arr)
print("Access 4th element of second row: ",my_arr[1, 3])

[[1 2 3 4]
 [5 6 7 8]]
Access 4th element of second row:  8


### Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [14]:
import numpy as np

my_arr = np.array([[[1, 2, 3, 4],[5, 6, 7, 8]], [[10, 15, 20, 25],[30, 35, 40, 45]]])

print(my_arr)
print("The third element of the second array inside first array is: " ,my_arr[0, 1, 2])

# Example Explained
# The first number represents the first dimension, which contains two arrays
# Since we selected 0, we are left with the first array

# The second number represents the second dimension, which also contains two arrays:
# Since we selected 1, we are left with the second array:

# The third number represents the third dimension, which contains four values:
# Since we selected 2, we end up with the third value:

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 15 20 25]
  [30 35 40 45]]]
The third element of the second array inside first array is:  7


In [15]:
import numpy as np

my_arr = np.array([[[1, 2, 3, 4],[5, 6, 7, 8]], [[10, 15, 20, 25],[30, 35, 40, 45]]])

print(my_arr)
print("The fourth element of the first array inside second array is: " ,my_arr[1, 0, 3])


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 15 20 25]
  [30 35 40 45]]]
The fourth element of the first array inside second array is:  25


### Negative Indexing
Use negative indexing to access an array from the end.


In [18]:
import numpy as np

my_arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(my_arr)
print("The last element of second array is: ",my_arr[1, -1])

[[1 2 3 4]
 [5 6 7 8]]
The last element of second array is:  8
