# NumPy Data Types
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - string
10. U - unicode string
11. V - fixed chunk of memory for other type ( void )

### Checking the Data Type

In [1]:
import numpy as np

my_arr = np.array([1, 2, 3, 4, 5])

print(my_arr.dtype)

int64


In [2]:
import numpy as np

my_arr = np.array(['apple', 'banana', 'cherry'])

print(my_arr.dtype)

<U6


### Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [7]:
import numpy as np

my_arr = np.array([1, 2, 3, 4, 5], dtype = "S")

print(my_arr)
print(my_arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [8]:
# Create an array with data type 4 bytes integer:
import numpy as np

my_arr = np.array([1, 2, 3, 4], dtype = "i4")

print(my_arr)
print(my_arr.dtype)

[1 2 3 4]
int32


In [1]:
# If a type is given in which elements can't be casted then NumPy will raise a ValueError.

In [2]:
import numpy as np

my_arr = np.array(["a", "1", "2", "3"], dtype = "i")

print(my_arr)

ValueError: invalid literal for int() with base 10: 'a'

### Converting Data Type
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [3]:
import numpy as np

my_arr = np.array([10.2, 15.3, 20.6])

# The data type can be specified using a string, like 'f' for float, 'i' for integer etc.
#  or you can use the data type directly like float for float and int for integer.
new_arr = my_arr.astype("i")

print(new_arr)
print(new_arr.dtype)

[10 15 20]
int32


In [4]:
# Change data type from float to integer by using (int) as parameter value:
import numpy as np

my_arr = np.array([10.2, 15.3, 20.6])

new_arr = my_arr.astype(int)

print(new_arr)
print(new_arr.dtype)

[10 15 20]
int64


In [5]:
# Change data type from integer to boolean:
import numpy as np

my_arr = np.array([15, 25, 0, 35])

new_arr = my_arr.astype(bool)

print(new_arr)
print(new_arr.dtype)

[ True  True False  True]
bool


# NumPy Array Copy vs View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

## COPY
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [2]:
# Make a copy, change the original array, and display both arrays:
import numpy as np

my_arr = np.array([1, 2, 3, 4, 5])

# Make a copy of array
copy_arr = my_arr.copy()

# Make change in original arra
my_arr[1] = 50

print(my_arr)
print(copy_arr)

# NOTE. The copy array will be unchange because we have only made change in original array.

[ 1 50  3  4  5]
[1 2 3 4 5]


## VIEW
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view

In [3]:
# Make a view, change the original array, and display both arrays:
my_arr = np.array([1, 2, 3, 4, 5])

view_arr = my_arr.view()
# Make changw in original array
my_arr[0] = 99

print(my_arr)
print(view_arr)

[99  2  3  4  5]
[99  2  3  4  5]


In [4]:
my_arr = np.array([1, 2, 3, 4, 5])

view_arr = my_arr.view()
# Make changw in view array
view_arr[2] = 88

print(my_arr)
print(view_arr)

[ 1  2 88  4  5]
[ 1  2 88  4  5]


### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [5]:
my_arr = np.array([1, 2, 3, 4, 5])

copy_arr = my_arr.copy()
view_arr = my_arr.view()

# In copy the array own the data, so here the base attribute will return None.
print(copy_arr.base)

# In View the array do not own the data, so here the base attribute will return original object.
print(view_arr.base)

None
[1 2 3 4 5]
