# NumPy Array Shape
The shape of an array is the number of elements in each dimension.



### Get the Shape
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.


In [2]:
import numpy as np

my_arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(my_arr)
print("The shape of array is: ", my_arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
The shape of array is:  (2, 4)


In [6]:
my_arr = np.array([1, 2, 3, 4, 6], ndmin=4)

print(my_arr)
print('The shape of array is :', my_arr.shape)

# NOTE. Integers at every index in tuple tells about the number of elements the corresponding dimension has.

[[[[1 2 3 4 6]]]]
The shape of array is : (1, 1, 1, 5)


# NumPy Array Reshaping
Reshaping means changing the shape of an array. The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.



### Reshape From 1-D to 2-D


In [8]:
my_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

new_arr = my_arr.reshape(3,3)

print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
my_arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = my_arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


### Reshape From 1-D to 3-D


In [10]:
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr_3d = arr_1d.reshape(2, 3, 2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
# The outermost dimension will have 2 arrays that contains 2 arrays, each with 3 elements:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr_3d = arr_1d.reshape(2, 2, 3)

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Multidimension into 1D array
It is also called flattening the array. We can use reshape(-1) to do this.

In [13]:
arr_2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

arr_1d = arr_2d.reshape(-1)

print(arr_1d)

[1 2 3 4 5 6 7 8]


In [19]:
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 3 elements:

arr_3d = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]], [[10, 15, 20],[25, 30, 35],[40, 45, 50]]])

arr_1d = arr_3d.reshape(-1)

print(arr_3d)
print(arr_1d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 15 20]
  [25 30 35]
  [40 45 50]]]
[ 1  2  3  4  5  6  7  8  9 10 15 20 25 30 35 40 45 50]
