# NumPy Joining Array
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

In [5]:
# We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis.
# If axis is not explicitly passed, it is taken as 0.

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.concatenate((arr1, arr2))

print(new_arr)

[1 2 3 4 5 6]


In [24]:
# Join two 2-D arrays along rows (axis=1):
import numpy as np

arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])

new_arr =np.concatenate((arr1, arr2), axis = 1)

print(new_arr)

# Note. axis 1 is out of bounds for array of dimension 1

[[1 2 5 6]
 [3 4 7 8]]


## Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.


In [25]:
# We pass a sequence of arrays that we want to join to the stack() method along with the axis.
# If axis is not explicitly passed it is taken as 0.

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.stack((arr1, arr2), axis = 1)

print(new_arr)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.stack((arr1, arr2))

print(new_arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.hstack((arr1, arr2))

print(new_arr)

[1 2 3 4 5 6]


### Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.


In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.vstack((arr1, arr2))

print(new_arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.


In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.dstack((arr1, arr2))

print(new_arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Array Splitting 
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [28]:
my_arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.array_split(my_arr, 3)

print(new_arr)

# NOTE. The return value is a list containing three arrays.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [31]:
# If the array has less elements than required, it will adjust from the end accordingly.
my_arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.array_split(my_arr, 4)

print(new_arr)

# NOTE. Note: We also have the method split() available but it will not adjust the elements
# when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Access Split Arrays
The return value of the array_split() method is a list containing each of the split as an array.

We can access them from the result just like any array element

In [32]:
my_arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.array_split(my_arr, 3)

print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

[1 2]
[3 4]
[5 6]


### Splitting 2-D Arrays
We will use the same syntax when splitting 2-D arrays.

In [33]:
# Split the one 2-D array into three 2-D arrays.

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [34]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


### Spliting Along Columns


In [40]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.vsplit(arr, 2)

print(newarr)
print("Access the split arrays")
print(newarr[0])
print(newarr[1])

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]
Access the split arrays
[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
