# NumPy Arrays Searching
We can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [2]:
# Find the indexes where the value is 5.

import numpy as np

my_arr = np.array([1, 2, 3, 5, 4, 5, 6, 5])
x = np.where(my_arr == 5)

print(x)

# NOTE. It will return a tuple: (array([3, 5, 7],)
# Which means that the value 5 is present at index 3, 5, and 7.

(array([3, 5, 7]),)


In [4]:
# Find the indexes where the values are even:

my_arr = np.array([1, 2, 3, 5, 4, 5, 6, 8, 5])
x =np.where(my_arr % 2 == 0)

print(x)

(array([1, 4, 6, 7]),)


In [5]:
# Find the indexes where the values are odd:

my_arr = np.array([1, 2, 3, 5, 4, 5, 6, 8, 5])
x =np.where(my_arr % 2 == 1)

print(x)

(array([0, 2, 3, 5, 8]),)


### Search Sorted
There is a method called searchsorted() which performs a binary search in the array,

and returns the index where the specified value would be inserted to maintain the search order.


In [9]:
# Find the indexes where the value 3 should be inserted:

my_arr = np.array([4, 5, 6, 7, 8])
z = np.searchsorted(my_arr, 3)

print(z)

# NOTE. The searchsorted() method is assumed to be used on sorted arrays.

0


In [8]:
# Find the indexes where the value 9 should be inserted:

my_arr = np.array([4, 5, 6, 7, 8])
z = np.searchsorted(my_arr, 9)

print(z)

5


### Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.


In [10]:
# Find the indexes where the value 5 should be inserted:

my_arr = np.array([4, 5, 6, 7, 8])
z = np.searchsorted(my_arr, 5, side = "right")

print(z)

2


### Search Multiple Values
To search for more than one value, use an array with the specified values.


In [14]:
# Find the indexes where the values 1, 3, and 5 should be inserted:

my_arr = np.array([2, 4, 6, 8])
z = np.searchsorted(my_arr, [1, 3, 5, 7])

print(z)

[0 1 2 3]


# NumPy Arrays Sorting
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [16]:
my_arr = np.array([3, 1, 4, 2, 5, 7, 6])
s_arr = np.sort(my_arr)

print(s_arr)

# NOTE. Note: This method returns a copy of the array, leaving the original array unchanged.

[1 2 3 4 5 6 7]


In [17]:
# We can also sort array of string.

birds_arr = np.array(["Eagle", "Parrot", "Falcon", "Crow"])
s_arr = np.sort(birds_arr)

print(s_arr)

['Crow' 'Eagle' 'Falcon' 'Parrot']


In [18]:
# Sort a boolean array:

b_arr = np.array([False, True, True, False, True])
s_arr = np.sort(b_arr)

print(s_arr)

[False False  True  True  True]


### Sorting a 2-D Array
If we use the sort() method on a 2-D array, both arrays will be sorted:


In [19]:
my_arr = np.array([[4, 5, 2],[7, 3, 8]])
s_arr = np.sort(my_arr)

print(s_arr)

[[2 4 5]
 [3 7 8]]


# NumPy Array Filter
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, We filter an array using a boolean index list.

In [22]:
my_arr = np.array([10, 20, 30, 40, 50])
filter_arr = [True, False, False, False, True]

new_arr = my_arr[filter_arr]
print(new_arr)

# NOTE. If the value at an index is True that element is contained in the filtered array,
# if the value at that index is False that element is excluded from the filtered array.

[10 50]


# NumPy Array Iterating
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

### Iterating -D Arrays
If we iterate on a 1-D array it will go through each element one by one.

In [25]:
my_arr = np.array([1, 2, 3, 4])

for element in my_arr:
    print(element)

1
2
3
4


### Iterating 2-D Arrays
In a 2-D array it will go through all the rows. We will use nested loop.


In [27]:
my_arr = np.array([[1, 2, 3], [4, 5, 6]])

for element in my_arr:
    print(element)

# NOTE. If we iterate on a n-D array it will go through n-1th dimension one by one.

[1 2 3]
[4 5 6]


In [28]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.

my_arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in my_arr:
    for y in x:
        print(y)

1
2
3
4
5
6


### Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.


In [29]:
my_arr = np.array([[[1, 2],[3, 4]], [[5, 6],[7, 8]]])

for x in my_arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8


### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations.
    
It solves some basic issues which we face in iteration.

In [31]:
my_arr = np.array([[[1, 2],[3, 4]], [[5, 6],[7, 8]]])

for x in np.nditer(my_arr):
    print(x)
    
# Soution. In basic for loops, 
# iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

1
2
3
4
5
6
7
8
