# Numpy Initialization Methods
We have some built in methods in numpy that help in initializing numpy array.


### Zeros Array
We will have all the elements 0 in this array.

In [1]:
import numpy as np

zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


### ones array
We will have all the elements 1 in this array

In [2]:
one_arr = np.ones((1,3))
print(one_arr)

[[1. 1. 1.]]


In [3]:
one_arr = np.ones((3,4))
print(one_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Full array
We will have all same elements based on given value.

In [4]:
full_arr = np.full((3,2), 5)
print(full_arr)

[[5 5]
 [5 5]
 [5 5]]


### Identity Matrix
In this array diagonal elements are ones and all other elements are zeros.

In [5]:
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
id_arr = np.eye(4)
print(id_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Empty Array

In [10]:
em_arr = np.empty(2)
print(em_arr)

[5.43230922e-312 7.29112202e-304]


### Evenly spaced array
Elements are evenly spaced based on step value

In [12]:
# Start from 2 and end with 10.

ev_arr = np.arange(2,10,2)
print(ev_arr)


[2 4 6 8]


In [13]:
# specific number of eqaully spaced values between a range : elements are equally spaced based on step value

ls_arr = np.linspace(1,10,4)
print(ls_arr)

[ 1.  4.  7. 10.]


### random values array
It will create an array with random value

In [14]:
# Float value array
rf_arr = np.random.rand(3,2)
print(rf_arr)

[[0.90338022 0.38896524]
 [0.47032256 0.1797007 ]
 [0.30465148 0.1200208 ]]


In [17]:
# Integer value array
# The randint() method takes a size parameter where you can specify the shape of an array.

ri_arr = np.random.randint(1,100, size = (3,3))
print(ri_arr)

[[38 37 10]
 [72 38 90]
 [27 95 55]]
