# Data Distribution
Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

# Random Distribution
A random distribution is a set of random numbers that follow a certain probability density function.

The random module offer methods that returns randomly generated data distributions.

### Choice() Method
We can generate random numbers based on defined probabilities using the choice() method of the random module.

The choice() method allows us to specify the probability for each value.

In [5]:
# Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
#The probability for the value to be 3 is set to be 0.1
#The probability for the value to be 5 is set to be 0.3
#The probability for the value to be 7 is set to be 0.6
#The probability for the value to be 9 is set to be 0

#The sum of all probability numbers should be 1.

from numpy import random

rn_arr = random.choice([3, 5, 7, 9], p = [0.1, 0.3, 0.6, 0.0], size = (100))

print(rn_arr)

# NOTE. The probability of 7 is high that's why we have more 7 in array.

[7 7 7 3 7 5 7 5 5 7 3 7 3 7 7 7 7 5 5 7 7 7 7 7 7 5 5 5 5 5 5 5 7 5 7 7 5
 3 7 5 7 5 7 3 5 3 5 5 7 7 7 5 7 7 3 3 7 5 7 7 7 7 7 7 7 7 7 5 7 7 5 7 7 7
 7 7 7 7 5 5 7 3 7 5 5 7 5 7 7 7 5 7 3 7 3 5 7 7 5 7]


### Choice() Mthod 2-D array
We can return arrays of any shape and size by specifying the shape in the size parameter.


In [6]:
rn_arr = random.choice([3, 5, 7, 9], p = [0.1, 0.3, 0.6, 0.0], size = (3,5))

print(rn_arr)

[[7 7 5 7 5]
 [3 7 7 3 3]
 [3 7 5 3 7]]
