# Mathematical Operations on Array
We can do Mathematical Operation on array.

In [1]:
import numpy as np

my_arr = np.array([10, 20, 30, 40])
print(my_arr)

[10 20 30 40]


In [3]:
my_arr = np.array([10, 20, 30, 40])

print(my_arr + 5)     # add a value in array
print(my_arr - 20)    # Subtract a value in array
print(my_arr * 8)     # Multiply a value in array
print(my_arr / 4)     # Divide a value in array

[15 25 35 45]
[-10   0  10  20]
[ 80 160 240 320]
[ 2.5  5.   7.5 10. ]


In [4]:
my_arr1 = np.array([1, 4, 8, 9])

print(my_arr1)

print(np.square(my_arr1))       # square of all array elements
print(np.sqrt(my_arr1))         # square root of all array elements

[1 4 8 9]
[ 1 16 64 81]
[1.         2.         2.82842712 3.        ]


## Muliple Arrays
We can do Mathematical operation on Multiple arrays as well.

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### Dot product
Computes the inner product of the two vectors and sum the results

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

32


### Transpose Array
Returns an array with axes transposed

In [8]:
my_arr2 = np.array([[1, 2, 3 ],[4, 5, 6]])

print(my_arr2)       # initial shape: 2,3
print(my_arr2.T)     # shape after transpose: 3,2

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# Statistical Functions
We can do Statistical operation on numpy array.


In [11]:
my_arr3 = np.array([[5, 10, 15, 20],[25, 30, 35, 40]])

print(my_arr3)

[[ 5 10 15 20]
 [25 30 35 40]]


In [12]:
my_arr3 = np.array([[5, 10, 15, 20],[25, 30, 35, 40]])

print("Statistical Operations")
print(np.sum(my_arr3))
print(np.mean(my_arr3))
print(np.median(my_arr3))
print(np.std(my_arr3))
print(np.min(my_arr3))
print(np.max(my_arr3))

Statistical Operations
180
22.5
22.5
11.4564392373896
5
40
