# Mathematical Operations on Array
We can do Mathematical Operation on array.

In [1]:
import numpy as np

my_arr = np.array([10, 20, 30, 40])
print(my_arr)

[10 20 30 40]


In [3]:
my_arr = np.array([10, 20, 30, 40])

print(my_arr + 5)     # add a value in array
print(my_arr - 20)    # Subtract a value in array
print(my_arr * 8)     # Multiply a value in array
print(my_arr / 4)     # Divide a value in array

[15 25 35 45]
[-10   0  10  20]
[ 80 160 240 320]
[ 2.5  5.   7.5 10. ]


In [4]:
my_arr1 = np.array([1, 4, 8, 9])

print(my_arr1)

print(np.square(my_arr1))       # square of all array elements
print(np.sqrt(my_arr1))         # square root of all array elements

[1 4 8 9]
[ 1 16 64 81]
[1.         2.         2.82842712 3.        ]


## Muliple Arrays
We can do Mathematical operation on Multiple arrays as well.

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


### Addition
The add() function sums the content of two arrays, and return the results in a new array.


In [20]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.add(arr1, arr2)
print(new_arr)

[5 7 9]


### Subtraction
The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.


In [23]:
arr1 = np.array([1,2,3,10])
arr2 = np.array([4,5,6,8])

new_arr = np.subtract(arr1, arr2)
print(new_arr)

[-3 -3 -3  2]


### Multiplication
The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.


In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.multiply(arr1, arr2)
print(new_arr)

[ 4 10 18]


### Division
The divide() function divides the values from one array with the values from another array, and return the results in a new array.


In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.divide(arr1, arr2)
print(new_arr)

[0.25 0.4  0.5 ]


### Power
The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.


In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.power(arr1, arr2)
print(new_arr)

[  1  32 729]


### Absolute Values
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute()

to avoid confusion with python's inbuilt math.abs()

In [29]:
# The absolute method will change negative elements of array into positive elements.

arr1 = np.array([1, -2, 3, 4, -5, -6])

new_arr = np.absolute(arr1)
print(new_arr)

[1 2 3 4 5 6]


## Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

1. truncation
2. fix
3. rounding
4. floor
5. ceil

### truncation
Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.


In [30]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [31]:
# it work the same as truncate.

arr = np.fix([-5.1687, 6.2437])

print(arr)

[-5.  6.]


### Round
The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.


In [37]:
arr = np.around(4.1967, 2)

print(arr)

4.2


### Floor
The floor() function rounds off decimal to nearest lower integer.


In [38]:
arr = np.floor([-6.1666, 4.6667])

print(arr)

[-7.  4.]


### Ceil
The ceil() function rounds off decimal to nearest upper integer.


In [40]:
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


## Summations
What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

In [42]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr1 = np.add(arr1, arr2)
new_arr2 = np.sum([arr1,arr2])     # In sum method the argument is pass as array

print(new_arr1)
print(new_arr2)

[5 7 9]
21


### Products
To find the product of the elements in an array, use the prod() function.


In [43]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

# NOTE. Returns: 24, because 1*2*3*4 = 24

24


### Dot product
Computes the inner product of the two vectors and sum the results

In [44]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

32


### Transpose Array
Returns an array with axes transposed

In [45]:
my_arr2 = np.array([[1, 2, 3 ],[4, 5, 6]])

print(my_arr2)       # initial shape: 2,3
print(my_arr2.T)     # shape after transpose: 3,2

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# Statistical Functions
We can do Statistical operation on numpy array.


In [46]:
my_arr3 = np.array([[5, 10, 15, 20],[25, 30, 35, 40]])

print(my_arr3)

[[ 5 10 15 20]
 [25 30 35 40]]


In [47]:
my_arr3 = np.array([[5, 10, 15, 20],[25, 30, 35, 40]])

print("Statistical Operations")
print(np.sum(my_arr3))
print(np.mean(my_arr3))
print(np.median(my_arr3))
print(np.std(my_arr3))
print(np.min(my_arr3))
print(np.max(my_arr3))

Statistical Operations
180
22.5
22.5
11.4564392373896
5
40


# Broadcasting
It is a mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes.

It eliminates the need for explicit loops or reshaping operations, making code more concise, readable and efficient.

Broadcasting Rules:
   1.  Compare shapes from right to left.
   2.  Dimensions must match or be 1.
   3. If one array has fewer dimensions, pad its shape on the left with 1s.
   4. Any dimension equal to 1 can stretch to match the other array.

In [48]:
# adding 1D with 0ne-element array to 1D with multi-element array.

a = np.array([1,2,3,4])      # 1D with multi-element array.
b = np.array([5])            # 1D with 0ne-element array
print(a+b) 

[6 7 8 9]


In [49]:
# adding 2D with 6-element array (2,3) to 1D with 3-element array.

c = np.array([[1,2,3], [4,5,6]])          # 2D with 6-element array (2,3)
d = np.array([10,20,30])                  # 1D with 6-element array
print(c+d) 

[[11 22 33]
 [14 25 36]]


# Vectorization
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

### Adding through Loop
One way to add elements of two lists is to iterate over both of the lists and then sum each elements.

In [50]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

# NOTE. This method become inefficient when dealing with large amount of data.

[5, 7, 9, 11]


### Adding Through Vectorization
NumPy has a built in method for this, called add(x, y) that will produce the same result.

It is fast, Efficient and helpful when dealing with large amount of data.

In [51]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]
